### ISSUE TITLE
Make the gun rounder.

### ISSUE THREAD

**Issue by frenchjam** [PsyPhy/ProjectDiskGun#1]

**Comment by frenchjam** [comment]
What do you mean by rounder? Do you want more facets?

**Comment by mikha42** [comment]
i do work now

**Comment by mikha42** [comment]
i think i did it. check it out though. its very smooth, it looks like a circle if you don't move.

**Comment by mikha42** [comment]
![gun pic](https://cloud.githubusercontent.com/assets/10961644/6154209/2d10415a-b22a-11e4-908d-125a95899fb9.png)

**Comment by mikha42** [comment]
drag and drop pictures into box and it will send them.

**Comment by frenchjam** [comment]
The picture here looks nice. When I sync with GitHub, the current version does not seem to include the new gun, though. I guess that it is related to the problem that you had with Unity. Can you check if you have the new gun in your current World1 scene and if so could you sync again with GitHub to make sure that I can get all the latest changes.

**Comment by mikha42** [comment]
See if it works now.

**Comment by frenchjam** [comment]
Yes, after the my latest sync with GitHub, the disc gun is nice and round. It looks good.
